// Interface strings in the six supported languages. Card contents (next action, replies, disclaimer) live in
// templates.ts. Register follows the existing templates: German "Sie", French "vous", Spanish "usted", Italian "tu",
// Portuguese neutral. Order of every entry: [en, de, fr, es, it, pt]. tests/i18n-unit.ts checks that every entry has
// six non-empty strings with the same {placeholders}.
import { createContext, useContext } from 'react';
import { LANGS, type Lang } from './types';

type Six = readonly [string, string, string, string, string, string];
const S = {
  // navigation / app shell
  tab_scan: ['Scan', 'Scannen', 'Scanner', 'Escanear', 'Scansiona', 'Digitalizar'],
  tab_saved: ['Saved', 'Gespeichert', 'Enregistrées', 'Guardadas', 'Salvate', 'Guardados'],
  tab_settings: ['Settings', 'Einstellungen', 'Réglages', 'Ajustes', 'Impostazioni', 'Definições'],
  nav_main: ['Main', 'Hauptmenü', 'Menu principal', 'Menú principal', 'Menu principale', 'Menu principal'],
  online: ['Online', 'Online', 'En ligne', 'En línea', 'Online', 'Online'],
  offline: ['Offline', 'Offline', 'Hors ligne', 'Sin conexión', 'Offline', 'Offline'],
  back_home: ['Home', 'Start', 'Accueil', 'Inicio', 'Home', 'Início'],
  err_process: ['Could not process this image: {msg}', 'Dieses Bild konnte nicht verarbeitet werden: {msg}', 'Impossible de traiter cette image : {msg}', 'No se ha podido procesar esta imagen: {msg}', 'Impossibile elaborare questa immagine: {msg}', 'Não foi possível processar esta imagem: {msg}'],
  note_no_text: ['No text could be read. Try a sharper, well-lit photo, held flat.', 'Es konnte kein Text gelesen werden. Versuchen Sie ein schärferes, gut beleuchtetes Foto, flach gehalten.', "Aucun texte n'a pu être lu. Essayez une photo plus nette, bien éclairée, prise à plat.", 'No se ha podido leer ningún texto. Pruebe con una foto más nítida, con buena luz y el papel plano.', 'Non è stato possibile leggere alcun testo. Prova con una foto più nitida, ben illuminata e con il foglio piatto.', 'Não foi possível ler nenhum texto. Experimente uma foto mais nítida, com boa luz e o papel plano.'],
  note_ai_nokey: ['AI mode is on but no API key is set; used offline rules.', 'Der KI-Modus ist an, aber kein API-Schlüssel ist gespeichert; es wurden die Offline-Regeln verwendet.', "Le mode IA est activé mais aucune clé API n'est enregistrée ; les règles hors ligne ont été utilisées.", 'El modo IA está activado pero no hay ninguna clave API; se han usado las reglas sin conexión.', 'La modalità IA è attiva ma non è impostata alcuna chiave API; sono state usate le regole offline.', 'O modo IA está ativo, mas não há chave de API; foram usadas as regras offline.'],
  note_ai_offline: ['Offline; used offline rules instead of AI mode.', 'Offline; statt des KI-Modus wurden die Offline-Regeln verwendet.', 'Hors ligne ; les règles hors ligne ont été utilisées à la place du mode IA.', 'Sin conexión; se han usado las reglas sin conexión en lugar del modo IA.', 'Offline; sono state usate le regole offline al posto della modalità IA.', 'Offline; foram usadas as regras offline em vez do modo IA.'],
  note_ai_failed: ['AI mode failed ({msg}); used offline rules.', 'Der KI-Modus ist fehlgeschlagen ({msg}); es wurden die Offline-Regeln verwendet.', 'Le mode IA a échoué ({msg}) ; les règles hors ligne ont été utilisées.', 'El modo IA ha fallado ({msg}); se han usado las reglas sin conexión.', 'La modalità IA non ha funzionato ({msg}); sono state usate le regole offline.', 'O modo IA falhou ({msg}); foram usadas as regras offline.'],
  note_low_ocr: ['The photo was hard to read (OCR confidence {pct}%), so results are likely incomplete or wrong. Retake it closer, flat and in good light.', 'Das Foto war schwer zu lesen (OCR-Sicherheit {pct} %), die Ergebnisse sind daher wahrscheinlich unvollständig oder falsch. Fotografieren Sie näher, flach und bei gutem Licht.', "La photo était difficile à lire (fiabilité OCR {pct} %) : les résultats sont probablement incomplets ou faux. Reprenez-la de plus près, à plat et avec une bonne lumière.", 'La foto era difícil de leer (fiabilidad OCR {pct} %), así que los resultados probablemente estén incompletos o sean erróneos. Repítala más cerca, con el papel plano y buena luz.', 'La foto era difficile da leggere (affidabilità OCR {pct}%), quindi i risultati sono probabilmente incompleti o sbagliati. Rifalla più da vicino, con il foglio piatto e con buona luce.', 'A foto era difícil de ler (fiabilidade OCR {pct}%), por isso os resultados estão provavelmente incompletos ou errados. Tire-a de novo mais perto, com o papel plano e boa luz.'],

  // capture screen
  eyebrow: ['Foreign-language paperwork, decoded', 'Fremdsprachige Post, entschlüsselt', 'Vos papiers en langue étrangère, décodés', 'Papeles en otro idioma, descifrados', 'Documenti in lingua straniera, decifrati', 'Papéis noutra língua, decifrados'],
  headline: ['What does this paper want from me?', 'Was will dieses Schreiben von mir?', 'Que me demande ce document ?', '¿Qué me pide este papel?', 'Cosa vuole da me questo foglio?', 'O que é que este papel quer de mim?'],
  lead: ["Photograph a document in a language you can't fully read. You get the deadline, the money at stake and the one next step, with the exact source text for each.", 'Fotografieren Sie ein Dokument in einer Sprache, die Sie nicht ganz verstehen. Sie bekommen die Frist, den Betrag und den nächsten Schritt, jeweils mit dem genauen Originaltext.', 'Photographiez un document dans une langue que vous ne lisez pas bien. Vous obtenez la date limite, la somme en jeu et la prochaine étape, chacune avec le texte source exact.', 'Fotografíe un documento en un idioma que no entiende del todo. Obtendrá el plazo, el dinero en juego y el siguiente paso, cada uno con el texto original exacto.', 'Fotografa un documento in una lingua che non capisci del tutto. Ottieni la scadenza, la somma in gioco e il prossimo passo, ciascuno con il testo originale esatto.', 'Fotografe um documento numa língua que não entende bem. Recebe o prazo, o dinheiro em jogo e o próximo passo, cada um com o texto original exato.'],
  take_photo: ['Take a photo', 'Foto aufnehmen', 'Prendre une photo', 'Hacer una foto', 'Scatta una foto', 'Tirar uma foto'],
  opens_camera: ['Opens the camera', 'Öffnet die Kamera', "Ouvre l'appareil photo", 'Abre la cámara', 'Apre la fotocamera', 'Abre a câmara'],
  choose_gallery: ['Choose from gallery', 'Aus Galerie wählen', 'Choisir dans la galerie', 'Elegir de la galería', 'Scegli dalla galleria', 'Escolher da galeria'],
  screenshots_ok: ['Screenshots work too', 'Auch Bildschirmfotos', "Les captures d'écran aussi", 'También capturas de pantalla', 'Anche screenshot', 'Capturas de ecrã também'],
  doc_language: ['Document language', 'Sprache des Dokuments', 'Langue du document', 'Idioma del documento', 'Lingua del documento', 'Língua do documento'],
  detect_auto: ['Detect automatically', 'Automatisch erkennen', 'Détecter automatiquement', 'Detectar automáticamente', 'Rileva automaticamente', 'Detetar automaticamente'],
  works_best: ['Works best with', 'Funktioniert am besten mit', 'Fonctionne le mieux avec', 'Funciona mejor con', 'Funziona meglio con', 'Funciona melhor com'],
  chip_fines: ['Parking & traffic fines', 'Park- & Bußgeldbescheiden', 'Amendes de stationnement et de circulation', 'Multas de aparcamiento y tráfico', 'Multe per sosta e traffico', 'Multas de estacionamento e trânsito'],
  chip_cancel: ['Hotel & airline cancellations', 'Hotel- & Flugstornierungen', "Annulations d'hôtel et de vol", 'Cancelaciones de hotel y vuelo', 'Cancellazioni di hotel e voli', 'Cancelamentos de hotel e voo'],
  chip_visa: ['Visa & entry letters', 'Visum- & Einreiseschreiben', "Courriers de visa et d'entrée", 'Cartas de visado y entrada', 'Lettere di visto e ingresso', 'Cartas de visto e entrada'],
  chip_medicine: ['Medicine labels', 'Arzneimittel-Etiketten', 'Étiquettes de médicaments', 'Etiquetas de medicamentos', 'Etichette di farmaci', 'Rótulos de medicamentos'],
  chip_rental: ['Rental move-in sheets', 'Wohnungsübergabeprotokollen', 'États des lieux de location', 'Hojas de entrada de alquiler', 'Verbali di consegna di affitto', 'Autos de entrega de arrendamento'],
  tip_photo: ['Hold the phone flat over the page, in good light, page filling the screen.', 'Halten Sie das Handy flach über die Seite, bei gutem Licht, die Seite füllt den Bildschirm.', "Tenez le téléphone à plat au-dessus de la page, avec une bonne lumière, la page remplissant l'écran.", 'Sostenga el móvil plano sobre la página, con buena luz y la página llenando la pantalla.', 'Tieni il telefono parallelo alla pagina, con buona luce e la pagina che riempie lo schermo.', 'Segure o telemóvel paralelo à página, com boa luz e a página a ocupar o ecrã.'],
  tip_private: ['Photos and cards stay on this phone. No account. Works offline.', 'Fotos und Karten bleiben auf diesem Handy. Kein Konto. Funktioniert offline.', 'Les photos et les fiches restent sur ce téléphone. Sans compte. Fonctionne hors ligne.', 'Las fotos y las tarjetas se quedan en este móvil. Sin cuenta. Funciona sin conexión.', 'Foto e schede restano su questo telefono. Nessun account. Funziona offline.', 'As fotos e os cartões ficam neste telemóvel. Sem conta. Funciona offline.'],
  tip_advice: ['Not a translator, and not legal or medical advice. Always check the original.', 'Kein Übersetzer und keine Rechts- oder medizinische Beratung. Prüfen Sie immer das Original.', "Ce n'est ni un traducteur, ni un conseil juridique ou médical. Vérifiez toujours l'original.", 'No es un traductor ni asesoramiento legal o médico. Compruebe siempre el original.', "Non è un traduttore né una consulenza legale o medica. Controlla sempre l'originale.", 'Não é um tradutor nem aconselhamento jurídico ou médico. Confira sempre o original.'],
  privacy_line: ['On-device text recognition · nothing uploaded', 'Texterkennung auf dem Gerät · nichts wird hochgeladen', "Reconnaissance du texte sur l'appareil · rien n'est envoyé", 'Reconocimiento de texto en el dispositivo · no se sube nada', 'Riconoscimento del testo sul dispositivo · nessun caricamento', 'Reconhecimento de texto no dispositivo · nada é enviado'],

  // first run
  intro_title: ['How it works', "So funktioniert's", 'Comment ça marche', 'Cómo funciona', 'Come funziona', 'Como funciona'],
  intro_1: ['Photograph a letter, ticket or label in a foreign language.', 'Fotografieren Sie einen Brief, Bescheid oder ein Etikett in einer fremden Sprache.', 'Photographiez un courrier, un avis ou une étiquette en langue étrangère.', 'Fotografíe una carta, una multa o una etiqueta en otro idioma.', 'Fotografa una lettera, una multa o un’etichetta in lingua straniera.', 'Fotografe uma carta, uma multa ou um rótulo noutra língua.'],
  intro_2: ['The app reads it on this phone and shows the deadline, the money at stake and what to do next, each with the exact text it came from.', 'Die App liest es auf diesem Handy und zeigt Frist, Betrag und nächsten Schritt, jeweils mit dem genauen Text, aus dem es stammt.', "L'application le lit sur ce téléphone et affiche la date limite, la somme en jeu et la prochaine étape, chacune avec le texte exact d'où elle vient.", 'La aplicación lo lee en este móvil y muestra el plazo, el dinero en juego y qué hacer después, cada uno con el texto exacto del que procede.', "L'app lo legge su questo telefono e mostra la scadenza, la somma in gioco e cosa fare dopo, ciascuno con il testo esatto da cui proviene.", 'A aplicação lê-o neste telemóvel e mostra o prazo, o dinheiro em jogo e o que fazer a seguir, cada um com o texto exato de onde vem.'],
  intro_3: ['The card can be wrong, so always check the original.', 'Die Karte kann falsch sein, prüfen Sie also immer das Original.', "La fiche peut se tromper : vérifiez toujours l'original.", 'La tarjeta puede equivocarse, así que compruebe siempre el original.', "La scheda può sbagliare, quindi controlla sempre l'originale.", 'O cartão pode estar errado, por isso confira sempre o original.'],
  try_sample: ['Try a sample document', 'Beispieldokument ausprobieren', 'Essayer un document exemple', 'Probar un documento de ejemplo', 'Prova un documento di esempio', 'Experimentar um documento de exemplo'],
  sample_hint: ['A made-up German parking ticket that comes with the app. Works offline.', 'Ein erfundener deutscher Strafzettel, der in der App enthalten ist. Funktioniert offline.', "Une fausse contravention allemande fournie avec l'application. Fonctionne hors ligne.", 'Una multa de aparcamiento alemana inventada que viene con la aplicación. Funciona sin conexión.', "Una multa tedesca inventata inclusa nell'app. Funziona offline.", 'Uma multa de estacionamento alemã fictícia incluída na aplicação. Funciona offline.'],
  got_it: ['Got it', 'Verstanden', "J'ai compris", 'Entendido', 'Ho capito', 'Percebi'],
  sample_err: ['Could not load the sample: {msg}', 'Das Beispiel konnte nicht geladen werden: {msg}', "Impossible de charger l'exemple : {msg}", 'No se ha podido cargar el ejemplo: {msg}', "Impossibile caricare l'esempio: {msg}", 'Não foi possível carregar o exemplo: {msg}'],

  // processing
  reading_title: ['Reading your document…', 'Ihr Dokument wird gelesen…', 'Lecture de votre document…', 'Leyendo su documento…', 'Lettura del documento…', 'A ler o seu documento…'],
  reading_page: ['Reading page {n}…', 'Seite {n} wird gelesen…', 'Lecture de la page {n}…', 'Leyendo la página {n}…', 'Lettura della pagina {n}…', 'A ler a página {n}…'],
  step_prepare: ['Preparing your photo', 'Foto wird vorbereitet', 'Préparation de la photo', 'Preparando la foto', 'Preparazione della foto', 'A preparar a foto'],
  step_orient: ['Checking orientation & language', 'Ausrichtung & Sprache prüfen', "Vérification de l'orientation et de la langue", 'Comprobando orientación e idioma', 'Controllo di orientamento e lingua', 'A verificar orientação e língua'],
  step_read: ['Reading the text', 'Text wird gelesen', 'Lecture du texte', 'Leyendo el texto', 'Lettura del testo', 'A ler o texto'],
  step_build: ['Building your action card', 'Ihre Karte wird erstellt', 'Création de votre fiche', 'Creando su tarjeta', 'Creazione della scheda', 'A criar o seu cartão'],
  progress: ['Progress', 'Fortschritt', 'Progression', 'Progreso', 'Avanzamento', 'Progresso'],
  current_step: ['Current step', 'Aktueller Schritt', 'Étape en cours', 'Paso actual', 'Passo corrente', 'Passo atual'],
  your_document: ['Your document', 'Ihr Dokument', 'Votre document', 'Su documento', 'Il tuo documento', 'O seu documento'],
  not_uploaded: ['Reading happens on this phone. The photo is not uploaded.', 'Das Lesen passiert auf diesem Handy. Das Foto wird nicht hochgeladen.', "La lecture se fait sur ce téléphone. La photo n'est pas envoyée.", 'La lectura se hace en este móvil. La foto no se sube.', 'La lettura avviene su questo telefono. La foto non viene caricata.', 'A leitura é feita neste telemóvel. A foto não é enviada.'],

  // card
  deadline: ['Deadline', 'Frist', 'Date limite', 'Plazo', 'Scadenza', 'Prazo'],
  expiry: ['Expiry / use by', 'Verfallsdatum', 'Date de péremption', 'Fecha de caducidad', 'Data di scadenza', 'Prazo de validade'],
  appointment: ['Appointment date', 'Termin', 'Date du rendez-vous', 'Fecha de la cita', "Data dell'appuntamento", 'Data da marcação'],
  money: ['Money at stake', 'Betrag', 'Somme en jeu', 'Dinero en juego', 'Somma in gioco', 'Dinheiro em jogo'],
  not_found: ['Not found', 'Nicht gefunden', 'Introuvable', 'No encontrado', 'Non trovato', 'Não encontrado'],
  next_action: ['Your next action', 'Ihr nächster Schritt', 'Votre prochaine étape', 'Su siguiente paso', 'Il tuo prossimo passo', 'O seu próximo passo'],
  what_to_do: ['What to do', 'Was zu tun ist', 'Que faire', 'Qué hacer', 'Cosa fare', 'O que fazer'],
  remind_me: ['Remind me', 'Erinnern', 'Me le rappeler', 'Recordármelo', 'Promemoria', 'Lembrar-me'],
  share: ['Share', 'Teilen', 'Partager', 'Compartir', 'Condividi', 'Partilhar'],
  copied: ['Copied ✓', 'Kopiert ✓', 'Copié ✓', 'Copiado ✓', 'Copiato ✓', 'Copiado ✓'],
  check_photo: ['Check the original photo', 'Originalfoto prüfen', 'Vérifier la photo originale', 'Comprobar la foto original', 'Controlla la foto originale', 'Confirmar a foto original'],
  hide_photo: ['Hide original', 'Original ausblenden', "Masquer l'original", 'Ocultar el original', "Nascondi l'originale", 'Ocultar o original'],
  show_photo: ['Show original photo', 'Originalfoto zeigen', 'Afficher la photo originale', 'Mostrar la foto original', 'Mostra la foto originale', 'Mostrar a foto original'],
  original_doc: ['Original document', 'Originaldokument', 'Document original', 'Documento original', 'Documento originale', 'Documento original'],
  mode_ai: ['AI mode', 'KI-Modus', 'Mode IA', 'Modo IA', 'Modalità IA', 'Modo IA'],
  mode_rules: ['Offline rules', 'Offline-Regeln', 'Règles hors ligne', 'Reglas sin conexión', 'Regole offline', 'Regras offline'],
  where_from: ['Where this comes from', 'Woher das stammt', "D'où ça vient", 'De dónde sale esto', 'Da dove viene', 'De onde vem isto'],
  rule_in_doc: ['Rule in the document:', 'Regel im Dokument:', 'Règle dans le document :', 'Regla en el documento:', 'Regola nel documento:', 'Regra no documento:'],
  start_in_doc: ['Start date in the document ({label}):', 'Startdatum im Dokument ({label}):', 'Date de départ dans le document ({label}) :', 'Fecha de inicio en el documento ({label}):', 'Data di inizio nel documento ({label}):', 'Data de início no documento ({label}):'],
  no_start: ["No start date found in the document. The app does not assume today's date.", 'Kein Startdatum im Dokument gefunden. Die App nimmt nicht das heutige Datum an.', "Aucune date de départ trouvée dans le document. L'application ne suppose pas la date du jour.", 'No se ha encontrado fecha de inicio en el documento. La aplicación no supone la fecha de hoy.', "Nessuna data di inizio trovata nel documento. L'app non presume la data di oggi.", 'Não foi encontrada data de início no documento. A aplicação não assume a data de hoje.'],
  calculation: ['Calculation: {calc}', 'Berechnung: {calc}', 'Calcul : {calc}', 'Cálculo: {calc}', 'Calcolo: {calc}', 'Cálculo: {calc}'],
  other_deadlines: ['Other deadlines in the document ({n})', 'Weitere Fristen im Dokument ({n})', 'Autres dates limites dans le document ({n})', 'Otros plazos en el documento ({n})', 'Altre scadenze nel documento ({n})', 'Outros prazos no documento ({n})'],
  all_dates: ['All dates found in the document ({n})', 'Alle Daten im Dokument ({n})', 'Toutes les dates du document ({n})', 'Todas las fechas del documento ({n})', 'Tutte le date nel documento ({n})', 'Todas as datas do documento ({n})'],
  all_amounts: ['All amounts found in the document ({n})', 'Alle Beträge im Dokument ({n})', 'Tous les montants du document ({n})', 'Todos los importes del documento ({n})', 'Tutti gli importi nel documento ({n})', 'Todos os valores do documento ({n})'],
  use: ['Use', 'Übernehmen', 'Utiliser', 'Usar', 'Usa', 'Usar'],
  date_unknown: ['Date unknown', 'Datum unbekannt', 'Date inconnue', 'Fecha desconocida', 'Data sconosciuta', 'Data desconhecida'],
  label_says: ['What the label says (quoted, not advice)', 'Was auf dem Etikett steht (Zitat, keine Beratung)', "Ce que dit l'étiquette (citation, pas un conseil)", 'Lo que dice la etiqueta (cita, no es un consejo)', "Cosa dice l'etichetta (citazione, non un consiglio)", 'O que diz o rótulo (citação, não é conselho)'],
  no_dosing_text: ['No dosing text found on the label.', 'Kein Dosierungstext auf dem Etikett gefunden.', "Aucun texte de posologie trouvé sur l'étiquette.", 'No se ha encontrado texto de dosificación en la etiqueta.', "Nessun testo sul dosaggio trovato sull'etichetta.", 'Não foi encontrado texto de posologia no rótulo.'],
  never_dosing: ['This app never gives dosing advice. Confirm with a pharmacist or doctor before taking any medicine.', 'Diese App gibt nie Dosierungsempfehlungen. Klären Sie vor der Einnahme jedes Medikaments alles mit einer Apotheke oder einem Arzt.', "Cette application ne donne jamais de conseil de dosage. Vérifiez avec un pharmacien ou un médecin avant de prendre un médicament.", 'Esta aplicación nunca da consejos de dosificación. Consulte a un farmacéutico o a un médico antes de tomar cualquier medicamento.', "Questa app non dà mai consigli sul dosaggio. Verifica con un farmacista o un medico prima di prendere qualsiasi farmaco.", 'Esta aplicação nunca dá conselhos de posologia. Confirme com um farmacêutico ou médico antes de tomar qualquer medicamento.'],
  draft_reply: ['Draft reply · {lang}', 'Antwortentwurf · {lang}', 'Brouillon de réponse · {lang}', 'Borrador de respuesta · {lang}', 'Bozza di risposta · {lang}', 'Rascunho de resposta · {lang}'],
  copy_lang: ['Copy {lang} text', 'Text auf {lang} kopieren', 'Copier le texte en {lang}', 'Copiar el texto en {lang}', 'Copia il testo in {lang}', 'Copiar o texto em {lang}'],
  same_reply: ["Same reply · {lang} (so you know what you're sending)", 'Dieselbe Antwort · {lang} (damit Sie wissen, was Sie senden)', 'Même réponse · {lang} (pour savoir ce que vous envoyez)', 'La misma respuesta · {lang} (para que sepa lo que envía)', 'Stessa risposta · {lang} (per sapere cosa stai inviando)', 'A mesma resposta · {lang} (para saber o que está a enviar)'],
  copy: ['Copy', 'Kopieren', 'Copier', 'Copiar', 'Copia', 'Copiar'],
  details: ['Details', 'Details', 'Détails', 'Detalles', 'Dettagli', 'Detalhes'],
  doc_type: ['Document type', 'Dokumenttyp', 'Type de document', 'Tipo de documento', 'Tipo di documento', 'Tipo de documento'],
  reference: ['Reference / case number', 'Aktenzeichen / Referenz', 'Référence / numéro de dossier', 'Referencia / número de expediente', 'Riferimento / numero di pratica', 'Referência / número do processo'],
  full_text: ['Full text read from the photo', 'Gesamter gelesener Text', 'Texte complet lu sur la photo', 'Texto completo leído de la foto', 'Testo completo letto dalla foto', 'Texto completo lido da foto'],
  ocr_conf: ['(OCR confidence {pct}%)', '(OCR-Sicherheit {pct} %)', '(fiabilité OCR {pct} %)', '(fiabilidad OCR {pct} %)', '(affidabilità OCR {pct}%)', '(fiabilidade OCR {pct}%)'],
  no_text_found: ['(no text found)', '(kein Text gefunden)', '(aucun texte trouvé)', '(no se ha encontrado texto)', '(nessun testo trovato)', '(nenhum texto encontrado)'],
  save_card: ['Save card', 'Speichern', 'Enregistrer', 'Guardar', 'Salva', 'Guardar'],
  saved: ['Saved', 'Gespeichert', 'Enregistrée', 'Guardada', 'Salvata', 'Guardado'],
  pdf: ['PDF', 'PDF', 'PDF', 'PDF', 'PDF', 'PDF'],
  export_pdf: ['Export PDF', 'Als PDF exportieren', 'Exporter en PDF', 'Exportar PDF', 'Esporta PDF', 'Exportar PDF'],
  new_scan: ['New scan', 'Neuer Scan', 'Nouveau scan', 'Nuevo escaneo', 'Nuova scansione', 'Nova digitalização'],
  save_error: ['Could not save on this phone ({msg}). Export a PDF instead.', 'Speichern auf diesem Handy nicht möglich ({msg}). Exportieren Sie stattdessen ein PDF.', "Impossible d'enregistrer sur ce téléphone ({msg}). Exportez plutôt un PDF.", 'No se ha podido guardar en este móvil ({msg}). Exporte un PDF en su lugar.', 'Impossibile salvare su questo telefono ({msg}). Esporta invece un PDF.', 'Não foi possível guardar neste telemóvel ({msg}). Exporte antes um PDF.'],
  save: ['Save', 'Speichern', 'Enregistrer', 'Guardar', 'Salva', 'Guardar'],
  cancel: ['Cancel', 'Abbrechen', 'Annuler', 'Cancelar', 'Annulla', 'Cancelar'],
  today: ['Today', 'Heute', "Aujourd'hui", 'Hoy', 'Oggi', 'Hoje'],
  tomorrow: ['Tomorrow', 'Morgen', 'Demain', 'Mañana', 'Domani', 'Amanhã'],
  in_days: ['in {n} days', 'in {n} Tagen', 'dans {n} jours', 'en {n} días', 'tra {n} giorni', 'daqui a {n} dias'],
  day_ago: ['1 day ago', 'vor 1 Tag', 'il y a 1 jour', 'hace 1 día', '1 giorno fa', 'há 1 dia'],
  days_ago: ['{n} days ago', 'vor {n} Tagen', 'il y a {n} jours', 'hace {n} días', '{n} giorni fa', 'há {n} dias'],

  // pages
  add_page: ['Add page', 'Seite hinzufügen', 'Ajouter une page', 'Añadir página', 'Aggiungi pagina', 'Adicionar página'],
  add_page_hint: ['Letter has more pages? Add them to the same card.', 'Mehrseitiges Schreiben? Fügen Sie die Seiten derselben Karte hinzu.', "Le courrier a plusieurs pages ? Ajoutez-les à la même fiche.", '¿La carta tiene más páginas? Añádalas a la misma tarjeta.', 'La lettera ha più pagine? Aggiungile alla stessa scheda.', 'A carta tem mais páginas? Adicione-as ao mesmo cartão.'],
  page_n: ['Page {n}', 'Seite {n}', 'Page {n}', 'Página {n}', 'Pagina {n}', 'Página {n}'],
  pages_n: ['{n} pages', '{n} Seiten', '{n} pages', '{n} páginas', '{n} pagine', '{n} páginas'],
  from_page: ['From the document (page {n}):', 'Aus dem Dokument (Seite {n}):', 'Dans le document (page {n}) :', 'Del documento (página {n}):', 'Dal documento (pagina {n}):', 'Do documento (página {n}):'],
  page_edited_note: ['Values you edited are kept; everything else was re-read from all pages.', 'Von Ihnen geänderte Werte bleiben; alles andere wurde aus allen Seiten neu gelesen.', 'Les valeurs que vous avez modifiées sont conservées ; le reste a été relu sur toutes les pages.', 'Los valores que ha editado se mantienen; el resto se ha vuelto a leer de todas las páginas.', 'I valori che hai modificato restano; il resto è stato riletto da tutte le pagine.', 'Os valores editados são mantidos; o resto foi relido de todas as páginas.'],

  // fields
  conf_high: ['Clear', 'Eindeutig', 'Clair', 'Claro', 'Chiaro', 'Claro'],
  conf_medium: ['Check this', 'Bitte prüfen', 'À vérifier', 'Revisar', 'Da verificare', 'Verificar'],
  conf_low: ['Guess', 'Vermutung', 'Supposition', 'Suposición', 'Ipotesi', 'Palpite'],
  conf_sr: ['Confidence:', 'Sicherheit:', 'Fiabilité :', 'Fiabilidad:', 'Affidabilità:', 'Fiabilidade:'],
  conf_title: ['How sure the app is about this value', 'Wie sicher sich die App bei diesem Wert ist', "Le degré de certitude de l'application pour cette valeur", 'Lo segura que está la aplicación de este valor', "Quanto l'app è sicura di questo valore", 'O grau de certeza da aplicação sobre este valor'],
  edited: ['Edited', 'Geändert', 'Modifié', 'Editado', 'Modificato', 'Editado'],
  edited_by_you: ['Edited by you', 'Von Ihnen geändert', 'Modifié par vous', 'Editado por usted', 'Modificato da te', 'Editado manualmente'],
  tap_to_edit: ['tap to edit', 'zum Bearbeiten tippen', 'touchez pour modifier', 'toque para editar', 'tocca per modificare', 'toque para editar'],
  from_doc: ['From the document:', 'Aus dem Dokument:', 'Dans le document :', 'Del documento:', 'Dal documento:', 'Do documento:'],
  not_in_text: ['The app did not find this in the text. Check the original, or tap to add it.', 'Die App hat das nicht im Text gefunden. Prüfen Sie das Original oder tippen Sie, um es einzutragen.', "L'application ne l'a pas trouvé dans le texte. Vérifiez l'original ou touchez pour l'ajouter.", 'La aplicación no lo ha encontrado en el texto. Compruebe el original o toque para añadirlo.', "L'app non l'ha trovato nel testo. Controlla l'originale o tocca per aggiungerlo.", 'A aplicação não encontrou isto no texto. Confira o original ou toque para o adicionar.'],

  // saved list
  saved_cards: ['Saved cards', 'Gespeicherte Karten', 'Fiches enregistrées', 'Tarjetas guardadas', 'Schede salvate', 'Cartões guardados'],
  stored_only: ['Stored only on this phone. Clearing your browser data removes them.', 'Nur auf diesem Handy gespeichert. Wenn Sie die Browserdaten löschen, sind sie weg.', 'Enregistrées uniquement sur ce téléphone. Effacer les données du navigateur les supprime.', 'Guardadas solo en este móvil. Si borra los datos del navegador, se eliminan.', 'Salvate solo su questo telefono. Cancellando i dati del browser vengono eliminate.', 'Guardados apenas neste telemóvel. Apagar os dados do navegador elimina-os.'],
  storage_hint: ["The browser may delete saved cards if you don't open this app for about a week (Safari does this). To keep them, add the app to your Home Screen (Safari: Share → Add to Home Screen), and export a PDF of anything important.", 'Der Browser kann gespeicherte Karten löschen, wenn Sie die App etwa eine Woche nicht öffnen (Safari tut das). Um sie zu behalten, legen Sie die App auf den Home-Bildschirm (Safari: Teilen → Zum Home-Bildschirm) und exportieren Sie Wichtiges als PDF.', "Le navigateur peut supprimer les fiches enregistrées si vous n'ouvrez pas l'application pendant environ une semaine (Safari le fait). Pour les garder, ajoutez l'application à l'écran d'accueil (Safari : Partager → Sur l'écran d'accueil) et exportez en PDF tout ce qui est important.", 'El navegador puede borrar las tarjetas guardadas si no abre la aplicación durante una semana aproximadamente (Safari lo hace). Para conservarlas, añada la aplicación a la pantalla de inicio (Safari: Compartir → Añadir a pantalla de inicio) y exporte en PDF lo importante.', "Il browser può eliminare le schede salvate se non apri l'app per circa una settimana (Safari lo fa). Per tenerle, aggiungi l'app alla schermata Home (Safari: Condividi → Aggiungi alla schermata Home) ed esporta in PDF ciò che è importante.", 'O navegador pode apagar os cartões guardados se não abrir a aplicação durante cerca de uma semana (o Safari faz isto). Para os manter, adicione a aplicação ao ecrã principal (Safari: Partilhar → Adicionar ao ecrã principal) e exporte em PDF o que for importante.'],
  overdue: ['Overdue', 'Überfällig', 'En retard', 'Vencidas', 'Scadute', 'Em atraso'],
  coming_up: ['Coming up', 'Demnächst', 'À venir', 'Próximas', 'In arrivo', 'A seguir'],
  no_deadline_found: ['No deadline found', 'Keine Frist gefunden', 'Aucune date limite trouvée', 'Sin plazo encontrado', 'Nessuna scadenza trovata', 'Sem prazo encontrado'],
  no_amount: ['No amount', 'Kein Betrag', 'Aucun montant', 'Sin importe', 'Nessun importo', 'Sem valor'],
  saved_on: ['Saved {date}', 'Gespeichert am {date}', 'Enregistrée le {date}', 'Guardada el {date}', 'Salvata il {date}', 'Guardado a {date}'],
  delete: ['Delete', 'Löschen', 'Supprimer', 'Eliminar', 'Elimina', 'Eliminar'],
  keep: ['Keep', 'Behalten', 'Garder', 'Conservar', 'Tieni', 'Manter'],
  delete_card: ['Delete card', 'Karte löschen', 'Supprimer la fiche', 'Eliminar tarjeta', 'Elimina scheda', 'Eliminar cartão'],
  no_saved: ['No saved cards yet. Scan a document and tap “Save card”.', 'Noch keine gespeicherten Karten. Scannen Sie ein Dokument und tippen Sie auf „Speichern“.', "Aucune fiche enregistrée. Scannez un document et touchez « Enregistrer ».", 'Aún no hay tarjetas guardadas. Escanee un documento y toque «Guardar».', 'Ancora nessuna scheda salvata. Scansiona un documento e tocca «Salva».', 'Ainda não há cartões guardados. Digitalize um documento e toque em «Guardar».'],
  loading: ['Loading', 'Wird geladen', 'Chargement', 'Cargando', 'Caricamento', 'A carregar'],

  // settings
  settings: ['Settings', 'Einstellungen', 'Réglages', 'Ajustes', 'Impostazioni', 'Definições'],
  your_language: ['Your language', 'Ihre Sprache', 'Votre langue', 'Su idioma', 'La tua lingua', 'A sua língua'],
  your_language_help: ['The app, next actions and the second copy of each reply use this language. Chosen from your phone at first start.', 'Die App, die nächsten Schritte und die zweite Fassung jeder Antwort verwenden diese Sprache. Beim ersten Start vom Handy übernommen.', "L'application, les prochaines étapes et la seconde version de chaque réponse utilisent cette langue. Reprise du téléphone au premier lancement.", 'La aplicación, los siguientes pasos y la segunda copia de cada respuesta usan este idioma. Se toma del móvil la primera vez.', "L'app, i prossimi passi e la seconda copia di ogni risposta usano questa lingua. Presa dal telefono al primo avvio.", 'A aplicação, os próximos passos e a segunda cópia de cada resposta usam esta língua. Escolhida a partir do telemóvel no primeiro arranque.'],
  doc_lang_help: ['Auto-detect reads the page twice (quick English pass, then the detected language), so picking the language is faster.', 'Die automatische Erkennung liest die Seite zweimal (kurz auf Englisch, dann in der erkannten Sprache); mit gewählter Sprache geht es schneller.', 'La détection automatique lit la page deux fois (rapidement en anglais, puis dans la langue détectée) : choisir la langue est plus rapide.', 'La detección automática lee la página dos veces (rápido en inglés y luego en el idioma detectado), así que elegir el idioma es más rápido.', 'Il rilevamento automatico legge la pagina due volte (veloce in inglese, poi nella lingua rilevata), quindi scegliere la lingua è più rapido.', 'A deteção automática lê a página duas vezes (rapidamente em inglês e depois na língua detetada), por isso escolher a língua é mais rápido.'],
  ai_title: ['AI mode (optional)', 'KI-Modus (optional)', 'Mode IA (facultatif)', 'Modo IA (opcional)', 'Modalità IA (facoltativa)', 'Modo IA (opcional)'],
  ai_help: ['Off by default. The app always works offline with built-in rules. If you turn this on and add your own xAI (Grok) API key, the text read from the photo (never the photo itself) is sent directly from this phone to xAI to fill in the card. Results are still checked: every value must quote text that really is in the document, and anything invalid falls back to the offline rules.', 'Standardmäßig aus. Die App funktioniert immer offline mit eingebauten Regeln. Wenn Sie dies einschalten und Ihren eigenen xAI-(Grok-)API-Schlüssel eintragen, wird der aus dem Foto gelesene Text (nie das Foto selbst) direkt von diesem Handy an xAI gesendet, um die Karte auszufüllen. Die Ergebnisse werden trotzdem geprüft: Jeder Wert muss Text zitieren, der wirklich im Dokument steht; alles Ungültige fällt auf die Offline-Regeln zurück.', "Désactivé par défaut. L'application fonctionne toujours hors ligne avec des règles intégrées. Si vous l'activez et ajoutez votre propre clé API xAI (Grok), le texte lu sur la photo (jamais la photo elle-même) est envoyé directement de ce téléphone à xAI pour remplir la fiche. Les résultats restent vérifiés : chaque valeur doit citer un texte réellement présent dans le document, et tout ce qui n'est pas valable revient aux règles hors ligne.", 'Desactivado por defecto. La aplicación siempre funciona sin conexión con reglas integradas. Si lo activa y añade su propia clave API de xAI (Grok), el texto leído de la foto (nunca la foto) se envía directamente desde este móvil a xAI para rellenar la tarjeta. Los resultados se siguen comprobando: cada valor debe citar texto que esté realmente en el documento, y lo que no sea válido vuelve a las reglas sin conexión.', "Disattivata per impostazione predefinita. L'app funziona sempre offline con regole integrate. Se la attivi e aggiungi la tua chiave API xAI (Grok), il testo letto dalla foto (mai la foto stessa) viene inviato direttamente da questo telefono a xAI per compilare la scheda. I risultati vengono comunque controllati: ogni valore deve citare un testo che è davvero nel documento, e ciò che non è valido torna alle regole offline.", 'Desligado por predefinição. A aplicação funciona sempre offline com regras incorporadas. Se o ligar e adicionar a sua própria chave de API da xAI (Grok), o texto lido da foto (nunca a própria foto) é enviado diretamente deste telemóvel para a xAI para preencher o cartão. Os resultados continuam a ser verificados: cada valor tem de citar texto que esteja mesmo no documento, e o que não for válido volta às regras offline.'],
  ai_key_warning: ["Your key is stored only in this browser's local storage on this phone. It is not in the app's code and is not sent anywhere except api.x.ai. That is fine for a personal prototype, but a real public launch needs a server proxy so keys never live on phones.", 'Ihr Schlüssel wird nur im lokalen Speicher dieses Browsers auf diesem Handy gespeichert. Er steht nicht im Code der App und wird nur an api.x.ai gesendet. Für einen persönlichen Prototyp ist das in Ordnung; ein echter öffentlicher Start braucht einen Server-Proxy, damit Schlüssel nie auf Handys liegen.', "Votre clé est stockée uniquement dans le stockage local de ce navigateur sur ce téléphone. Elle n'est pas dans le code de l'application et n'est envoyée qu'à api.x.ai. C'est acceptable pour un prototype personnel, mais un vrai lancement public nécessite un proxy serveur pour que les clés ne soient jamais sur les téléphones.", 'Su clave se guarda solo en el almacenamiento local de este navegador en este móvil. No está en el código de la aplicación y solo se envía a api.x.ai. Vale para un prototipo personal, pero un lanzamiento público real necesita un proxy en un servidor para que las claves nunca estén en los móviles.', "La tua chiave è salvata solo nella memoria locale di questo browser su questo telefono. Non è nel codice dell'app e viene inviata solo a api.x.ai. Va bene per un prototipo personale, ma un vero lancio pubblico richiede un proxy su server, così le chiavi non restano mai sui telefoni.", 'A sua chave fica guardada apenas no armazenamento local deste navegador neste telemóvel. Não está no código da aplicação e só é enviada para api.x.ai. Serve para um protótipo pessoal, mas um lançamento público a sério precisa de um proxy num servidor para que as chaves nunca fiquem nos telemóveis.'],
  ai_toggle: ['Use AI mode when online', 'KI-Modus verwenden, wenn online', 'Utiliser le mode IA en ligne', 'Usar el modo IA con conexión', 'Usa la modalità IA quando online', 'Usar o modo IA quando online'],
  ai_key: ['xAI API key', 'xAI-API-Schlüssel', 'Clé API xAI', 'Clave API de xAI', 'Chiave API xAI', 'Chave de API da xAI'],
  model: ['Model', 'Modell', 'Modèle', 'Modelo', 'Modello', 'Modelo'],
  save_key: ['Save key', 'Schlüssel speichern', 'Enregistrer la clé', 'Guardar clave', 'Salva chiave', 'Guardar chave'],
  remove_key: ['Remove key', 'Schlüssel entfernen', 'Supprimer la clé', 'Quitar clave', 'Rimuovi chiave', 'Remover chave'],
  key_saved: ['Saved on this phone.', 'Auf diesem Handy gespeichert.', 'Enregistrée sur ce téléphone.', 'Guardada en este móvil.', 'Salvata su questo telefono.', 'Guardada neste telemóvel.'],
  key_removed: ['Key removed.', 'Schlüssel entfernt.', 'Clé supprimée.', 'Clave eliminada.', 'Chiave rimossa.', 'Chave removida.'],
  privacy: ['Privacy', 'Datenschutz', 'Confidentialité', 'Privacidad', 'Privacy', 'Privacidade'],
  privacy_1: ['No account, no analytics, no trackers.', 'Kein Konto, keine Analyse, keine Tracker.', 'Pas de compte, pas de statistiques, pas de traceurs.', 'Sin cuenta, sin analíticas, sin rastreadores.', 'Nessun account, nessuna analisi, nessun tracker.', 'Sem conta, sem análises, sem rastreadores.'],
  privacy_2: ['Text recognition (Tesseract OCR) runs on this phone. Language data for English, German, French, Spanish, Italian and Portuguese is stored with the app so it works offline.', 'Die Texterkennung (Tesseract OCR) läuft auf diesem Handy. Sprachdaten für Englisch, Deutsch, Französisch, Spanisch, Italienisch und Portugiesisch sind in der App gespeichert, damit sie offline funktioniert.', "La reconnaissance du texte (Tesseract OCR) s'exécute sur ce téléphone. Les données des langues anglaise, allemande, française, espagnole, italienne et portugaise sont stockées avec l'application pour qu'elle fonctionne hors ligne.", 'El reconocimiento de texto (Tesseract OCR) se ejecuta en este móvil. Los datos de inglés, alemán, francés, español, italiano y portugués se guardan con la aplicación para que funcione sin conexión.', "Il riconoscimento del testo (Tesseract OCR) avviene su questo telefono. I dati di inglese, tedesco, francese, spagnolo, italiano e portoghese sono salvati con l'app, così funziona offline.", 'O reconhecimento de texto (Tesseract OCR) é feito neste telemóvel. Os dados de inglês, alemão, francês, espanhol, italiano e português ficam guardados com a aplicação para funcionar offline.'],
  privacy_3: ["Photos and saved cards stay in this browser's storage on this phone.", 'Fotos und gespeicherte Karten bleiben im Speicher dieses Browsers auf diesem Handy.', 'Les photos et les fiches enregistrées restent dans le stockage de ce navigateur sur ce téléphone.', 'Las fotos y las tarjetas guardadas se quedan en el almacenamiento de este navegador en este móvil.', 'Le foto e le schede salvate restano nella memoria di questo browser su questo telefono.', 'As fotos e os cartões guardados ficam no armazenamento deste navegador neste telemóvel.'],
  delete_all: ['Delete all saved cards…', 'Alle gespeicherten Karten löschen…', 'Supprimer toutes les fiches…', 'Eliminar todas las tarjetas…', 'Elimina tutte le schede…', 'Eliminar todos os cartões…'],
  delete_all_yes: ['Yes, delete all cards', 'Ja, alle Karten löschen', 'Oui, tout supprimer', 'Sí, eliminar todas', 'Sì, elimina tutte', 'Sim, eliminar todos'],
  all_deleted: ['All saved cards deleted.', 'Alle gespeicherten Karten gelöscht.', 'Toutes les fiches ont été supprimées.', 'Se han eliminado todas las tarjetas.', 'Tutte le schede sono state eliminate.', 'Todos os cartões foram eliminados.'],
  about: ['About', 'Über die App', 'À propos', 'Acerca de', 'Informazioni', 'Sobre'],
  about_1: ['Action Card (working name) · prototype v0.1. Not a translator, not legal or medical advice: it can be wrong, so always check the original document.', 'Action Card (Arbeitstitel) · Prototyp v0.1. Kein Übersetzer, keine Rechts- oder medizinische Beratung: Die App kann sich irren, prüfen Sie also immer das Originaldokument.', "Action Card (nom provisoire) · prototype v0.1. Ni traducteur, ni conseil juridique ou médical : elle peut se tromper, vérifiez donc toujours le document original.", 'Action Card (nombre provisional) · prototipo v0.1. No es un traductor ni asesoramiento legal o médico: puede equivocarse, así que compruebe siempre el documento original.', "Action Card (nome provvisorio) · prototipo v0.1. Non è un traduttore né una consulenza legale o medica: può sbagliare, quindi controlla sempre il documento originale.", 'Action Card (nome provisório) · protótipo v0.1. Não é um tradutor nem aconselhamento jurídico ou médico: pode errar, por isso confira sempre o documento original.'],
  about_install: ['Install: iPhone Safari → Share → Add to Home Screen. Android Chrome → menu → Install app.', 'Installieren: iPhone Safari → Teilen → Zum Home-Bildschirm. Android Chrome → Menü → App installieren.', "Installer : iPhone Safari → Partager → Sur l'écran d'accueil. Android Chrome → menu → Installer l'application.", 'Instalar: iPhone Safari → Compartir → Añadir a pantalla de inicio. Android Chrome → menú → Instalar aplicación.', "Installa: iPhone Safari → Condividi → Aggiungi alla schermata Home. Android Chrome → menu → Installa app.", 'Instalar: iPhone Safari → Partilhar → Adicionar ao ecrã principal. Android Chrome → menu → Instalar aplicação.'],
  about_tech: ['Technical note: Google ML Kit text recognition is only available to native Android/iOS apps, so this web app uses Tesseract.js (WebAssembly) instead.', 'Technischer Hinweis: Die Texterkennung von Google ML Kit gibt es nur für native Android-/iOS-Apps, daher nutzt diese Web-App stattdessen Tesseract.js (WebAssembly).', "Note technique : la reconnaissance de texte Google ML Kit n'est disponible que pour les applications natives Android/iOS ; cette application web utilise donc Tesseract.js (WebAssembly).", 'Nota técnica: el reconocimiento de texto de Google ML Kit solo está disponible para aplicaciones nativas de Android/iOS, por eso esta aplicación web usa Tesseract.js (WebAssembly).', "Nota tecnica: il riconoscimento del testo di Google ML Kit è disponibile solo per app native Android/iOS, quindi questa web app usa Tesseract.js (WebAssembly).", 'Nota técnica: o reconhecimento de texto do Google ML Kit só está disponível para aplicações nativas Android/iOS, por isso esta aplicação web usa o Tesseract.js (WebAssembly).'],
  show_intro: ['Show the introduction again', 'Einführung erneut zeigen', "Revoir l'introduction", 'Ver de nuevo la introducción', "Mostra di nuovo l'introduzione", 'Ver novamente a introdução'],

  // share / calendar / pdf
  sh_deadline: ['Deadline: {v}', 'Frist: {v}', 'Date limite : {v}', 'Plazo: {v}', 'Scadenza: {v}', 'Prazo: {v}'],
  sh_amount: ['Amount: {v}', 'Betrag: {v}', 'Montant : {v}', 'Importe: {v}', 'Importo: {v}', 'Valor: {v}'],
  sh_ref: ['Reference: {v}', 'Aktenzeichen: {v}', 'Référence : {v}', 'Referencia: {v}', 'Riferimento: {v}', 'Referência: {v}'],
  sh_next: ['Next step: {v}', 'Nächster Schritt: {v}', 'Prochaine étape : {v}', 'Siguiente paso: {v}', 'Prossimo passo: {v}', 'Próximo passo: {v}'],
  sh_footer: ['Made with Action Card. It can be wrong: check the original document.', 'Erstellt mit Action Card. Kann falsch sein: Prüfen Sie das Originaldokument.', "Créé avec Action Card. Peut se tromper : vérifiez le document original.", 'Hecho con Action Card. Puede equivocarse: compruebe el documento original.', "Creato con Action Card. Può sbagliare: controlla il documento originale.", 'Feito com o Action Card. Pode estar errado: confira o documento original.'],
  ics_title: ['{title}: deadline', '{title}: Frist', '{title} : date limite', '{title}: plazo', '{title}: scadenza', '{title}: prazo'],
  ics_alarm: ['{title}: deadline in 3 days', '{title}: Frist in 3 Tagen', '{title} : date limite dans 3 jours', '{title}: el plazo vence en 3 días', '{title}: scadenza tra 3 giorni', '{title}: prazo daqui a 3 dias'],
  ics_check: ['Check the original document: this card can be wrong.', 'Prüfen Sie das Originaldokument: Diese Karte kann falsch sein.', 'Vérifiez le document original : cette fiche peut se tromper.', 'Compruebe el documento original: esta tarjeta puede equivocarse.', 'Controlla il documento originale: questa scheda può sbagliare.', 'Confira o documento original: este cartão pode estar errado.'],
  pdf_conf: ['Confidence: {v}', 'Sicherheit: {v}', 'Fiabilité : {v}', 'Fiabilidad: {v}', 'Affidabilità: {v}', 'Fiabilidade: {v}'],
  pdf_edited: [' (edited by you)', ' (von Ihnen geändert)', ' (modifié par vous)', ' (editado por usted)', ' (modificato da te)', ' (editado manualmente)'],
  pdf_source: ['Source text: "{v}"', 'Originaltext: "{v}"', 'Texte source : "{v}"', 'Texto original: "{v}"', 'Testo originale: "{v}"', 'Texto original: "{v}"'],
  pdf_days_left: ['{n} days left on {date}', 'noch {n} Tage am {date}', 'encore {n} jours au {date}', 'quedan {n} días a {date}', 'mancano {n} giorni al {date}', 'faltam {n} dias em {date}'],
  pdf_days_ago: ['{n} days ago on {date}', 'vor {n} Tagen am {date}', 'il y a {n} jours au {date}', 'hace {n} días a {date}', '{n} giorni fa al {date}', 'há {n} dias em {date}'],
  pdf_no_start: ["No start date printed in the document; today's date is NOT assumed.", 'Kein Startdatum im Dokument; das heutige Datum wird NICHT angenommen.', "Aucune date de départ dans le document ; la date du jour n'est PAS supposée.", 'No hay fecha de inicio en el documento; NO se supone la fecha de hoy.', 'Nessuna data di inizio nel documento; la data di oggi NON viene presunta.', 'Não há data de início no documento; a data de hoje NÃO é assumida.'],
  pdf_other: ['Other deadline: {v}', 'Weitere Frist: {v}', 'Autre date limite : {v}', 'Otro plazo: {v}', 'Altra scadenza: {v}', 'Outro prazo: {v}'],
  pdf_reply_same: ['SAME REPLY ({lang})', 'DIESELBE ANTWORT ({lang})', 'MÊME RÉPONSE ({lang})', 'LA MISMA RESPUESTA ({lang})', 'STESSA RISPOSTA ({lang})', 'A MESMA RESPOSTA ({lang})'],
  pdf_mode: ['Mode: {v}', 'Modus: {v}', 'Mode : {v}', 'Modo: {v}', 'Modalità: {v}', 'Modo: {v}'],
  pdf_ocr: ['OCR confidence: {v}', 'OCR-Sicherheit: {v}', 'Fiabilité OCR : {v}', 'Fiabilidad OCR: {v}', 'Affidabilità OCR: {v}', 'Fiabilidade OCR: {v}'],
  pdf_full_text: ['FULL OCR TEXT', 'GESAMTER OCR-TEXT', 'TEXTE OCR COMPLET', 'TEXTO OCR COMPLETO', 'TESTO OCR COMPLETO', 'TEXTO OCR COMPLETO'],
  pdf_photos: ['PHOTOS OF THE ORIGINAL', 'FOTOS DES ORIGINALS', "PHOTOS DE L'ORIGINAL", 'FOTOS DEL ORIGINAL', "FOTO DELL'ORIGINALE", 'FOTOS DO ORIGINAL'],
} as const satisfies Record<string, Six>;

export type Key = keyof typeof S;
export const STRINGS: Record<Key, Six> = S;
const IDX: Record<Lang, number> = Object.fromEntries(LANGS.map((l, i) => [l, i])) as Record<Lang, number>;

export function tr(lang: Lang, key: Key, vars?: Record<string, string | number>): string {
  let s: string = S[key][IDX[lang] ?? 0] || S[key][0];
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.split(`{${k}}`).join(String(v));
  return s;
}
export type TFn = (key: Key, vars?: Record<string, string | number>) => string;
export const makeT = (lang: Lang): TFn => (key, vars) => tr(lang, key, vars);

/** Language of the phone, if the app supports it (first start only; afterwards the saved choice wins). */
export function detectLanguage(langs: readonly string[] = typeof navigator !== 'undefined' ? (navigator.languages?.length ? navigator.languages : [navigator.language]) : []): Lang {
  for (const l of langs) {
    const base = (l || '').toLowerCase().split(/[-_]/)[0] as Lang;
    if ((LANGS as readonly string[]).includes(base)) return base;
  }
  return 'en';
}

export const UiLang = createContext<Lang>('en');
export const useLang = () => useContext(UiLang);
export const useT = (): TFn => makeT(useContext(UiLang));
